### ISSUE TITLE
Can't use --config parameter

### ISSUE THREAD

**Issue by utgarda** [solutious/rudy#56]
Can't specify a config file from command line. Using the same files by copying them to ~/.rudy/config works ok.
    > ruby --version
    ruby 1.8.7 (2010-01-10 patchlevel 249) [x86_64-linux]
    > rudy --version
    Rudy version: 0.9.8.017
    > rudy -C ~/devenv/keys/amatsaev/rudy_config_amatsaev machines
    ERROR (TypeError): can't convert Array into String
    > ls ~/devenv/keys/amatsaev/rudy_config_amatsaev
    /home/etsvigun/devenv/keys/amatsaev/rudy_config_amatsaev
    > rudy -C "/home/etsvigun/devenv/keys/aws-biotech/config" machines
    ERROR (TypeError): can't convert Array into String

**Comment by utgarda** [comment]
With debug output:

```
> rudy machines
Machine group stage-master is not running.

> rudy --debug -C "/home/etsvigun/devenv/keys/aws-biotech/config" machines
D:  CRITERIA: {:environment=>:stage, :region=>:"us-east-1", :zone=>:"us-east-1b", :role=>:app, :rtype=>"m"}
D:  SELECT: select * from rudy_state  where environment='stage' and region='us-east-1' and zone='us-east-1b' and role='app' and rtype='m'
ERROR (TypeError): can't convert Array into String
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/aws/sdb.rb:221:in `digest'
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/aws/sdb.rb:221:in `call'
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/aws/sdb.rb:86:in `select'
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/metadata.rb:84:in `select'
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/metadata.rb:119:in `list'
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/machines.rb:20:in `list'
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/cli/base.rb:156:in `get_metadata'
```

**Comment by utgarda** [comment]
Oops , didn't mean to close. Debug output:

```
> rudy machines
Machine group stage-master is not running.

> rudy --debug -C "/home/etsvigun/devenv/keys/aws-biotech/config" machines
D:  CRITERIA: {:environment=>:stage, :region=>:"us-east-1", :zone=>:"us-east-1b", :role=>:app, :rtype=>"m"}
D:  SELECT: select * from rudy_state  where environment='stage' and region='us-east-1' and zone='us-east-1b' and role='app' and rtype='m'
ERROR (TypeError): can't convert Array into String
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/aws/sdb.rb:221:in `digest'
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/aws/sdb.rb:221:in `call'
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/aws/sdb.rb:86:in `select'
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/metadata.rb:84:in `select'
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/metadata.rb:119:in `list'
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/machines.rb:20:in `list'
/usr/lib64/ruby/gems/1.8/gems/rudy-0.9.8.017/bin/../lib/rudy/cli/base.rb:156:in `get_metadata'
```
